In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_excel(r"C:\Users\smrvr\Downloads\synthetic_credit_accounts_all_buckets.xlsx")
df.head()

,customer_id,customer_name,account_id,outstanding_balance,bill_generation_date,due_date,payment_date,snapshot_date
0,CUST1003,Ishaan Mehta,ACC20099,102016.73,2026-06-29,2026-07-19,2026-07-02,2026-09-30
1,CUST1004,Radhika Kapoor,ACC20004,178231.99,2026-07-30,2026-08-19,2026-08-15,2026-09-30
2,CUST1005,Aarav Gupta,ACC20005,2092078.40,2026-06-17,2026-07-08,2026-06-20,2026-09-30
3,CUST1007,Manish Mehta,ACC20007,422769.57,2026-06-30,2026-07-21,2026-07-04,2026-09-30
4,CUST1008,Meera Gupta,ACC20008,43325.90,2026-06-18,2026-07-03,2026-06-25,2026-09-30

In [13]:
df['dpd'] = (df['due_date'] - df['payment_date']).dt.days
df.head()

,customer_id,customer_name,account_id,outstanding_balance,bill_generation_date,due_date,payment_date,snapshot_date,dpd
0,CUST1003,Ishaan Mehta,ACC20099,102016.73,2026-06-29,2026-07-19,2026-07-02,2026-09-30,17
1,CUST1004,Radhika Kapoor,ACC20004,178231.99,2026-07-30,2026-08-19,2026-08-15,2026-09-30,4
2,CUST1005,Aarav Gupta,ACC20005,2092078.40,2026-06-17,2026-07-08,2026-06-20,2026-09-30,18
3,CUST1007,Manish Mehta,ACC20007,422769.57,2026-06-30,2026-07-21,2026-07-04,2026-09-30,17
4,CUST1008,Meera Gupta,ACC20008,43325.90,2026-06-18,2026-07-03,2026-06-25,2026-09-30,8

In [15]:
conditions = [
                df['dpd'] <= 0,
                df['dpd'].between(1, 30),
                df['dpd'].between(31, 60),
                df['dpd'].between(61, 90)
            ]

category = ['bucket0', 'bucket1', 'bucket2', 'bucket3']

In [16]:
df['bucket'] = np.select(conditions, category, default='bucket4')

In [17]:
df.head()

,customer_id,customer_name,account_id,outstanding_balance,bill_generation_date,due_date,payment_date,snapshot_date,dpd,bucket
0,CUST1003,Ishaan Mehta,ACC20099,102016.73,2026-06-29,2026-07-19,2026-07-02,2026-09-30,17,bucket1
1,CUST1004,Radhika Kapoor,ACC20004,178231.99,2026-07-30,2026-08-19,2026-08-15,2026-09-30,4,bucket1
2,CUST1005,Aarav Gupta,ACC20005,2092078.40,2026-06-17,2026-07-08,2026-06-20,2026-09-30,18,bucket1
3,CUST1007,Manish Mehta,ACC20007,422769.57,2026-06-30,2026-07-21,2026-07-04,2026-09-30,17,bucket1
4,CUST1008,Meera Gupta,ACC20008,43325.90,2026-06-18,2026-07-03,2026-06-25,2026-09-30,8,bucket1

In [22]:
summary = pd.pivot_table(df, index='bucket',aggfunc={'customer_id':'count','outstanding_balance':'sum'}).reset_index()

summary['%age_acct'] = ((summary['customer_id']/summary['customer_id'].sum())*100).round(2)

summary['%age_balance'] = ((summary['outstanding_balance']/summary['outstanding_balance'].sum())*100).round(2)

summary

    bucket  customer_id  outstanding_balance  %age_acct  %age_balance
0  bucket0           20           4426462.10      28.57         15.02
1  bucket1           44          24269696.87      62.86         82.37
2  bucket2            2            201252.75       2.86          0.68
3  bucket3            2            256253.75       2.86          0.87
4  bucket4            2            311254.75       2.86          1.06